### ISSUE TITLE
pub get error

### ISSUE THREAD

**Issue by kseregal** [Pajn/ElasticDart#3]
I'm having an error When i run "pub get". 
```
Resolving dependencies...
Incompatible version constraints on quiver:
- angular 4.0.0 depends on version >=0.22.0 <0.26.0
- angular_components 0.6.0 depends on version >=0.22.0 <0.26.0
- warehouse 0.1.0 depends on version >=0.20.0 <0.22.0
```

```
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.6.0
  elastic_dart: ^0.2.3
```
